// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeoozpujgfqqniqaasje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhlb296cHVqZ2ZxcW5pcWFhc2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDAxMjUsImV4cCI6MjA2MjI3NjEyNX0.WYPCzlyFxexb-fLp4OXgZjnyJHeTXTCJtxa_iSV3rH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);